datasource:
  database:
    names: shardingmarketing,marketing-tikiv,marketing-tiflash,marketing-doris,marketing-bi,marketing-log,marketing-datamap
    defaultSource: shardingmarketing
    shardingmarketing:
      name: shardingmarketing
      jdbc-url: jdbc:mysql://tidb-w-marketing.brapp.com:4000/marketing?useUnicode=true&characterEncoding=UTF-8&connectTimeout=3000&socketTimeout=300000&autoReconnect=false&failOverReadOnly=false&useConfigs=maxPerformance
      username: ENC(mysql-prod-ai-marketing-user)
      password: ENC(mysql-prod-ai-marketing-password)
      type: com.zaxxer.hikari.HikariDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      minimum-idle: 10 # 最小空闲连接数
      maximum-pool-size: 300 # 最大连接池数量
      connection-timeout: 60000 # 获取连接超时时间，单位毫秒
      idle-timeout: 300000 # 连接空闲超时时间，单位毫秒
      max-lifetime: 1800000 # 连接最大生命周期，单位毫秒（30分钟）
      keepalive-time: 30000 # 连接保活时间，单位毫秒
      connection-test-query: select 1 # 连接测试查询
    marketing-tikiv:
      name: marketing-tikiv
      type: com.zaxxer.hikari.HikariDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://tidb-w-marketing.brapp.com:4000/marketing?useUnicode=true&characterEncoding=UTF-8&connectTimeout=3000&socketTimeout=300000&autoReconnect=false&failOverReadOnly=false&useConfigs=maxPerformance
      username: ENC(mysql-prod-ai-marketing-user)
      password: ENC(mysql-prod-ai-marketing-password)
      minimum-idle: 5 # 最小空闲连接数
      maximum-pool-size: 30 # 最大连接池数量
      connection-timeout: 60000 # 获取连接超时时间，单位毫秒
      idle-timeout: 300000 # 连接空闲超时时间，单位毫秒
      max-lifetime: 1800000 # 连接最大生命周期，单位毫秒（30分钟）
      keepalive-time: 30000 # 连接保活时间，单位毫秒
      connection-test-query: select 1 # 连接测试查询
    marketing-tiflash:
      name: marketing-tiflash
      type: com.zaxxer.hikari.HikariDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://tidb-tiflash-marketing.brapp.com:4020/marketing?useUnicode=true&characterEncoding=UTF-8&connectTimeout=3000&socketTimeout=300000&autoReconnect=false&failOverReadOnly=false&useConfigs=maxPerformance
      username: ENC(mysql-prod-ai-marketing-user)
      password: ENC(mysql-prod-ai-marketing-password)
      minimum-idle: 4 # 最小空闲连接数
      maximum-pool-size: 4 # 最大连接池数量
      connection-timeout: 60000 # 获取连接超时时间，单位毫秒
      idle-timeout: 300000 # 连接空闲超时时间，单位毫秒
      max-lifetime: 1800000 # 连接最大生命周期，单位毫秒（30分钟）
      keepalive-time: 30000 # 连接保活时间，单位毫秒
      connection-test-query: select 1 # 连接测试查询
    marketing-doris:
      name: marketing-doris
      type: com.zaxxer.hikari.HikariDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://doris-w-marketing.brapp.com:6030/marketing
      username: ENC(mysql-prod-ai-marketing-user)
      password: ENC(mysql-prod-ai-marketing-password)
      minimum-idle: 4 # 最小空闲连接数
      maximum-pool-size: 4 # 最大连接池数量
      connection-timeout: 60000 # 获取连接超时时间，单位毫秒
      idle-timeout: 300000 # 连接空闲超时时间，单位毫秒
      max-lifetime: 1800000 # 连接最大生命周期，单位毫秒（30分钟）
      keepalive-time: 30000 # 连接保活时间，单位毫秒
      connection-test-query: select 1 # 连接测试查询
    marketing-bi:
      name: marketing-bi
      type: com.zaxxer.hikari.HikariDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://doris-w-marketing.brapp.com:6030/marketing_bi
      username: ENC(mysql-prod-ai-marketing-bi-user)
      password: ENC(mysql-prod-ai-marketing-bi-password)
      minimum-idle: 20 # 最小空闲连接数
      maximum-pool-size: 20 # 最大连接池数量
      connection-timeout: 60000 # 获取连接超时时间，单位毫秒
      idle-timeout: 300000 # 连接空闲超时时间，单位毫秒
      max-lifetime: 1800000 # 连接最大生命周期，单位毫秒（30分钟）
      keepalive-time: 30000 # 连接保活时间，单位毫秒
      connection-test-query: select 1 # 连接测试查询
    marketing-log:
      name: marketing-log
      type: com.zaxxer.hikari.HikariDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://tidb-w-marketing.brapp.com:4000/marketing_log?useUnicode=true&characterEncoding=UTF-8&connectTimeout=3000&socketTimeout=300000&autoReconnect=false&failOverReadOnly=false&useConfigs=maxPerformance
      username: ENC(mysql-prod-ai-marketing-log-user)
      password: ENC(mysql-prod-ai-marketing-log-password)
      minimum-idle: 5 # 最小空闲连接数
      maximum-pool-size: 300 # 最大连接池数量
      connection-timeout: 60000 # 获取连接超时时间，单位毫秒
      idle-timeout: 300000 # 连接空闲超时时间，单位毫秒
      max-lifetime: 1800000 # 连接最大生命周期，单位毫秒（30分钟）
      keepalive-time: 30000 # 连接保活时间，单位毫秒
      connection-test-query: select 1 # 连接测试查询
    marketing-datamap:
      name: marketing-datamap
      type: com.zaxxer.hikari.HikariDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://doris-w-marketing.brapp.com:6030/marketing_data_map
      username: ENC(mysql-prod-marketing-data-map-user)
      password: ENC(mysql-prod-marketing-data-map-pass)
      minimum-idle: 20 # 最小空闲连接数
      maximum-pool-size: 20 # 最大连接池数量
      connection-timeout: 60000 # 获取连接超时时间，单位毫秒
      idle-timeout: 300000 # 连接空闲超时时间，单位毫秒
      max-lifetime: 1800000 # 连接最大生命周期，单位毫秒（30分钟）
      keepalive-time: 30000 # 连接保活时间，单位毫秒
      connection-test-query: select 1 # 连接测试查询
      replicationAllocation: tag.location.default:1

eureka:
  client:
    service-url.defaultZone: http://192.168.21.20:18000/eureka/,http://192.168.21.29:18000/eureka/

spring:
  rabbitmq:
    zw:
      addresses: strategy-rabbitmq-zw-01.brapp.com:5672,strategy-rabbitmq-zw-02.brapp.com:5672,strategy-rabbitmq-zw-03.brapp.com:5672
      username: strategy_distribute
      password: Rz453hoEjUb37j8v
      publisher-confirms: true
      publisher-returns: true
      virtual-host: marketing-flow
    yz:
      addresses: strategy-rabbitmq-yz-01.brapp.com:5672,strategy-rabbitmq-yz-02.brapp.com:5672
      username: strategy_distribute
      password: Rz453hoEjUb37j8v
      publisher-confirms: true
      publisher-returns: true
      virtual-host: marketing-flow
    secondary:
      addresses: rabbitmq2.brapp.com:5671
      username: rabbitmq
      password: rabbitmq
      virtual-host: common
    listener:
      retry:
        enabled: true
        max-attempts: 5
        initial-interval: 3000
      acknowledge-mode: manual
      default-requeue-rejected: false
      auto-startup: true
  web:
    interceptors.enabled: true
  sql.source: prod
cluster:
  flag: ${CONF_CLUSTER}
otherConfig:
  huaXiangInterface:
    getReport: http://CLOUD-HX-RIBBON/huaxiang/v1/get_report
  sanxiangzhiliInterface:
    sanxiang_url: http://zh-service/v1/getData
    haina_url: http://HAINA-SERVICE/query
  alarm:
    secretKey: b58783d4b67f942166f2ffad298080e4
    appName: marketing
    outsideSecretKey: 11e6a1a63c10d2855d662a0265ea91c4
    outsideAppName: marketing-out
  userCenter:
    appName: marketing-api
    appSecretKey: 77786bf195aa73044af33f8fce6c0441
  encodeMapping:
    appName: marketing
    appSecretKey: d37f90c97204a2ef3fe774fc5f106cf5
  warning:
    pageSize: 5000
    apiUrl: http://compass-api.100credit.com/api/loan-warning-api/loanStrategy/v2/query
    path: /opt/data/inloan/download/marketing/
    sftpHost: brsftp3.brapp.com
    sftpPort: 9999
    sftpUser: BRmarketing
    sftpPwd: gKjTC62qUJMKigEyvn01@_2021.06.07
  proxy:
    proxy_host: squid-proxy2.brapp.com
    proxy_port: 3128
    proxy_username: spmarketing
    proxy_password: t0jI8xLw
    proxy_host_zw: 192.168.22.169
  mom:
    appSecretKey: 0eccd42aceae3d2f557fad6e393d7ebe
    appName: marketing_query_producer
    destinationName: marketing_query_log
api:
  intelligentCustomerService:
    baseUrl: http://pdai.brapp.com/helios-app-api
    pushUserUrl: ${api.intelligentCustomerService.baseUrl}/third/process/data  #推送智能客服接口
  robotAiApiService:
    baseUrl: http://pdai.brapp.com/robotai-api-service
    robotOutboundUrl: ${api.robotAiApiService.baseUrl}/api/robotOutbound  #转化推送智能客服
  dass:
    baseUrl: http://daas.huiyunai.com
    postHermesUserData: ${api.dass.baseUrl}/csos-daas/call/postHermesUserData
    postBlackList: ${api.dass.baseUrl}/csos-daas/call/postBlackList # 黑名单数据推送
    postRealTimeUserData: ${api.dass.baseUrl}/csos-daas/call/postRealTimeUserData # 实时单条用户名单数据推送
    postTransferData: ${api.dass.baseUrl}/csos-daas/call/postDealData # 转化数据推送
    aesKey: MgoTm8GxuxTUc6y5
    SecretKey: MIICeAIBADANBgkqhkiG9w0BAQEFAASCAmIwggJeAgEAAoGBAKm7vv0ZdB36H8sGL2YZWAPM3sQ+tMbfoPp71KncNzOzMMqd9KiK9tPrfeoApo+xXBZFvid8f+1BxiyU7/bHrxiIFvawfzTt0PTj/gYcM9k0gMMUmomGNir9PMzV2WWBDpvSLUSoWX56yk3LhUB4rHXrj5pUIpO0pEr5b9cPQbZBAgMBAAECgYEAkSXIkdBuiCQZhBjp97m8lqNf7RpipZ8fnpS+q/NyEXgvRVYGnwsXQOqlZrLfvQnC4hkKH+JL06znt8A15SemB0NizbDmFvtsi+tQQm9qK8jvMkdo6zVeXlNjJ2kDVu98WFDK3EEukWTQXiYTdX6paKiFQnWQwV/EKlb/Bi3lfEECQQDclPdFCptoKDv52HEqs4UbsGY/yO4ZbZXTPst1w0EKjhFIn9jcoFPBoO3o4URPM8ENeBZv8bpU0djGO2nCfAGFAkEAxPymAEbUmtHH893JILrfo65O85K5MmGNR/NSdn4uBjD9E0R1cWB3SHlfDUv9+r0GtuQasLSp3cvJI5OY2sdgjQJBALmurHfx9eA3/kTTbnADrokgdPI8sjG1jenFcoAvXREFhoccB/GxBNB6J8th1Z7Wcixkan7RfYjpHRHB8cVFngECQFy0tn8s1oPiNKMtfql7qSKENz3kkGoIhRAWkHmZmplpVsFJl6f7CUg/bp94Yxgs+8r5ASKmc8chUBEBNo/IA0UCQQCt75iTugjsjbZUvoYHwZ9A7Bf7vfG7sOI3cismFzARUpSUPN6dEht4X4Z2AdC9HXXS+Mb3vFaCIK+h3WDZeZJt
    isProxy: 1
    ibuBaseUrl: http://ibu.pushapi.huiyunai.com
    batchHermesUserData: ${api.dass.ibuBaseUrl}/ibu-daas/api/batchHermesUserData
    ibuAk: d87a6e0ab4dc2903
    ibuSk: fbd1478a51d88954
  customerService:
    apiCode: 4000296
  pushTransfer:
    robotAi:
      baseUrl: http://robotai-api-service/api
      robotOutboundUrl: ${api.pushTransfer.robotAi.baseUrl}/robotOutbound
      tailor:
        # eg: "{'apiCode':'true',apiCode:'false'}"
        apiCodeMap: "{'3710012':'true','7410846':'true','7410787':'true','7410784':'true'}"
  product-management:
    url: http://production.100credit.com/api/getProductionList.do?firstBusinessCode=A10&spreadStatus=5,2,3,4,0
    productTypeUrl: http://production.100credit.com/api/getProductionTypes.do
  bi:
    baseUrl: http://script-govern.100credit.cn
    executeTask: ${api.bi.baseUrl}/api/distribute/offlineBatch/executeTask
  biocloo:
    baseUrl: https://callcenter.biocloo.com.cn
    blackList: ${api.biocloo.baseUrl}/api/middle/robotai/v1/process_data
    isProxy: true
  hxCar:
    baseUrl: http://haoyunlailai.cn:6001
    carList: ${api.hxCar.baseUrl}/open_api/v1/car_list
    cityList: ${api.hxCar.baseUrl}/open_api/v1/city_list
    commitClue: ${api.hxCar.baseUrl}/open_api/v1/commit_clue
    isProxy: true
  antaios:
    baseUrl: http://pdai.brapp.com/antaios-app-api
    pushUserUrl: ${api.antaios.baseUrl}/antaios/third/process/resource
  rsxk:
    baseUrl: https://mdp.shurongdai.cn
    queryCallStatus: ${api.rsxk.baseUrl}/mdp-thinker-facade/api/queryCallStatus
    isProxy: true
  imbpApiService:
    baseUrl: http://pdai.brapp.com/antaios-app-api
    lineBaseInfoUrl: ${api.imbpApiService.baseUrl}/antaios/third/ibmp/gateway/groupByLineSupplier
  mock:
    baseUrl: http://marketing-inner-api
    redisUrl: ${api.mock.baseUrl}/mockRedis/queryMockConfig
  cybotstar:
    baseUrl: https://www.cybotstar.cn
    dialogUrl: ${api.cybotstar.baseUrl}/openapi/v1/conversation/dialog/
    isProxy: true
  qifu:
    baseUri: https://gws-bps.daikuan.360.cn
    baseCuDongZhiUri: https://gws-bps.daikuan.360.cn
    qrySleepUserRealMessageUrl: ${api.qifu.baseCuDongZhiUri}/api/gws/bps/gateway/operation/batchQrySleepUserRealMessage
    qryUserRealMessageUrl: ${api.qifu.baseCuDongZhiUri}/api/gws/bps/gateway/agent/operation/batchQryUserRealMessage
    saveReachDeleteRecordUrl: ${api.qifu.baseUri}/api/gws/bps/gateway/agent/operation/agentOperationSaveReachDeleteRecord
    saveReachDeleteRecordCuDongZhiUrl: ${api.qifu.baseCuDongZhiUri}/api/gws/bps/gateway/agent/operation/agentOperationActSaveReachDeleteRecord
    qryCallRealTimeUrl: ${api.qifu.baseCuDongZhiUri}/api/gws/bps/gateway/operation/callRealTimeQuery
    qifuPublicKey: "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAklMx0hZ1QqNZ+zavehNklYY8dvhIyg1wN4S8Bg+VZ6a1+dEDyy0b0nhXXZ+TwRc5zbHakE0XMo0Rssfi7KHQiOEhj65lxI/uODIK46yYy5IJKYJePyp9hPNT5vSfujF+R6QQ1/B3moyV5HNSAaFGGTdfxOA0jMg618PyhIfZjFpgXMiTp54bmUPVH34XvPKLnH8Sh1ITNK4ozxdKZg0vkz/Ob5kfYwSzmL8oio7TFEpFhXGdU15ymx5Hd8VCTJ9LEuS4m3FVMc2IVqlm8trEq+ZJQkvAtUVMPW19Ia7mg877pU5FKcBHKv3GL7sahc6nMIC3s+UajvjD65NqPD3DbQIDAQAB"
    appId: "qifu2bairong"
    brPublicKey: "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAxCYC32ffpgmFXEIIDsRX4S5G1KO+rgGv5dxrmk0SeHKsaiOqvpOP0kVPnC4k4vyf9PmHr/bMmwAFICvOfk3OCZthRHjgMegThwkKrOIkWc5pddnKsu4n8fsIW7HuVSMA87weK+HgWZmg17ygssKVdAWfsgYHMkuAikrdETdeyAUqCMAjUm8OVLyf7Aoc3VJcnezbACYCwUrCW/eGEY+GQQTHkxY+6BUMMG1qjYKTl/LFYOcyGISrhFUKWUoz5BRGhKYk+/0CsVgdZ9gm+JOhO2fNaJUPjSPNfUOWQueNo1ModpERN0Ri4uI9uZGREFVT8vs+nGloq1kPdq9IKwYPxwIDAQAB"
    brPrivateKey: "MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDEJgLfZ9+mCYVcQggOxFfhLkbUo76uAa/l3GuaTRJ4cqxqI6q+k4/SRU+cLiTi/J/0+Yev9sybAAUgK85+Tc4Jm2FEeOAx6BOHCQqs4iRZzml12cqy7ifx+whbse5VIwDzvB4r4eBZmaDXvKCywpV0BZ+yBgcyS4CKSt0RN17IBSoIwCNSbw5UvJ/sChzdUlyd7NsAJgLBSsJb94YRj4ZBBMeTFj7oFQwwbWqNgpOX8sVg5zIYhKuEVQpZSjPkFEaEpiT7/QKxWB1n2Cb4k6E7Z81olQ+NI819Q5ZC542jUyh2kRE3RGLi4j25kZEQVVPy+z6caWirWQ92r0grBg/HAgMBAAECggEADFS3aYQGM1H16E7eYs9FFwrpuQRyQE4q2LB6s0CVIK1U2XdUjJaKPBXPY2ojN4HaLHRja1SAmF3v9I3MdXQ+t6vk+YD/1yNX1u1ilmvBDURErPv8GjOOn0/AvsL40LFapff1jZytlfRqgCWDlLlW2+xelbp7SVYlxoveSe7JLpnIFtoSy+Vg12fS6/unulUKzwZTKdWwDuITwQ6UwfBqpbAZ3o6P0ZXGz3bWf4LyAsMZtCIM8qzoQECXq3stwoCeMqDNVezBU0/jtOq64fnIL0YVTA2zBZwgZ+JoMsR0beLmfZBatVvaT8Rnac/0CdpDhHEmc5w1dNpBhoy/lytDAQKBgQD/wdyXbG7teydStnuPnXivC3gdfvmc+DK/1V/N7QJwYYt9KLNfcCaklZUdACkEH1FbP50SXBko/jhKuqAVpAX0IcSXgMg9PLYBEb9Q14pkoHp5RugyhZcDHU8/6pUTQq1L122QZ6ZEEKUW44yM/EIAfkr7py9xnjp2Ag9wQzWkdwKBgQDEVarGrlDb9GJ0PhiC74XZECYQgh1eC5IhJoJ69/0kaACGpYNI14V+pG+LSyXEzVCb4uucNhdR/F3fLiVRmCQmcNyVg4bWWjZNvxRgBuXPLiwsupeLzHMQtkXavu4dxhhqwoDwTPkbnSFdoF+ej3VqZvol1MAcw5GHA2VNeMlTMQKBgQDKxPFWYFLGF4jCrAjkgO2ookg14nCWQbVCoDHXutvfK4cC0Nz9gpYwkKNrHbBnI0lGNfYbE0ejV4JbxQCch7Fsr8UEdMbMvjByQpbSykBfrVfMhSocvAtRHdCyFRLh9VAdvAuSnIqWlje9IOVS9cCCUZ6zTAZyZwdkfhetYqvJ2wKBgHUCYT77kHEmGq8Qeuc9/NU6jJT2Fq5/0t0y6DyFIzbZTMbySWXWHFc3hMrNRHsfqdTdznFQw2E3OHLUO6V/OLw4Mx5gPrHtHcQEBw6bzcZFzEn0AnFsrX7eQo91js/ryY2G0fVkymmsob/83j/PW7jIGnkFbGE4JLkESxF61PFhAoGAYYieiABFNJeZcb0tK6t5fIyLnsEaiqvIvKQquo52jSuUcH7K/y7mL2vdm6I0rwY+CDaBIpXBoXAI3Ud2ayWNR5Ya97f5+sajElTz5WEhI/FwKdzQUPK6mfx5AVRwpHTX2E6ZL7mlihWA4PwCtcfWaE6Can2UhnBMq29pz6CqteA="
    appIdAI: "qifu2bairong"
    qifuAIPublicKey: "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAjGACj1cr/Px32zBL0CbV022nOAyWARpjppyp/E3mfknvScep5dI8ybcfx6n9QlsVJRvBiIPvvwfXo5AaN6jwXtxp0dWlk68GlHmdrNd0+JEnqsi9HPF4afIuGjgm7xRcn32ZOiz/1MzMjzWF7kk7CXN0RuGqGg3iDZBllXq76MSXDdiB0IkwuJba5dDdhvV9VXRSu+oi5NZ0adgd3u5wnrEdBgDXpl2Acgin8L5uGUr3dFeOk3kvvwFDn/4WaTN9TrAbFZDfcZFpzJF9k4+BJFFt7ba1StUWL+/W9plvBtBXAXgmLPOc2wRekzSMqt7XRP198OoU3y2GA7i6C33djwIDAQAB"
    brAIPrivateKey: "MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCG8Fai8ZzIzqSypypVtDDASYJm8PDgif/+o0HkGuxFG1j8F9FtVsVq63/MIbfT1qC6gxs3C2+YF4FzeC2Wrq+fxlsRyCACYr+foOeBL7+h1hMyU4F05IjXbvGgjmlkinR6E710usHm7OVxcZIK0zkqAQo/Qm4e+OkXAp+Nl1wYmlr5mjdJr7eeg8wq1YHXMU6jV4ei4/o7eHmR/bALVpjf0r6fx5iff4Awy6ePsTRYEfbqlT+W33B9dZ8xjcmwY2Xhr60lR6b3iaJftezAeYxOrqfnGn/bSy5JBHkwvelJOA+ikmtdNw1eJggmrjVpqKnqtEj44ocXAYyWJPOrldEhAgMBAAECggEAKQGokmPyTWPe0RvT1a+okQbFxhq6WMIXNX7Pa05zNp0U8acbUaro25EtiQ9GGe5DceqdvqCPDR03jaubzwrO/DL/QewbLh5sNUpkj/G+vqObudN+p9M7cpyYeT5N8OvScbbGAE8w1chwAYWN6BRAbu9Z+ddqN6dUzlVRv2mb5y2vpPNHlsquoTFL6XA+j1rc5DOPmD19Sbkb23L9K1tQ2q5DYt3qf/WNsa/OQ47BR+GKENtDDRbkoAuGAZDVUFeQ5msSktNup6ippSYXk0XW3imBpqFOs0O9TPvFQuEQxQ0FQIA53L168Fm26rbXnWjQztlVbymZELB71EhYrzQD8QKBgQDNpeStJ3ArE47H3dNgPE2b3YyqkkU3KAFOIWM6rpzgrA+LdpKsV0AaH/mdqvaqHDr7Ql6mW1fhBspcS0/t45+TTVUKwGXt7SPGuBZyy7THFJG/O2TBpbAkDwjVbio+/0L+E6pl9jHyVNdLcZdRvFgFNq0xw1Fn37GXoWKRWNPVQwKBgQCn+lyvluG/f2Ozfb+mhTmceFqtMwDlOfH7aQI1N2QpIyqfRjBHKViSPeSZtkl3LQwSGFWag295x5iFAZweUSZRzvf0U6Gw4I3XxnnUouVxhZYzlP9agat8XFCnHpTaLm0/3UvxffW8gqQLrUBnTHEcGGpfB+wFvFtdUhO2MD+nywKBgQCDBpu4p1QUXhWuymsO+d0I3hPt6dwn1Flgim1Kyk4x5+7PkPDK1ZyGCLFl/7PBltMNm6/qlnBbc5QjUejPTSQzGiaA/yzydxFAX7IN2jSIU1a5XQJJT2P21Y1vTw2jrcflUmpTJJWWLPAvpWQgM7xxNfELr8KCSEhCsBS5PrtZOQKBgEMl6+MtN3TroZlgzTnty8fmvKi72MHJVhggNAe96sYfDqy4zBfGSWe8YiOoINoJIegh3iZ0IB3YUfnpWNUtr1nImIoM3HfubAUzjAQaUgn9Uruv9hvh9gEyjfMgYHSPVpDPD8qrhY4j0xvv1+zzO8v1XqA6dHkegI9ffg24X9ndAoGBAMU7Bn0L7d0THpuIjp8X+k0JiYEQUuF2Qv5IE46CUIZ8ZP2vB3vAYd32a4+wQJkAHlzbm8r96jPQcMvsx3/E+Ak7ULIgETdwms5kkMsoSO3DWCRhiMb12+E5fRpNCqxNqkA9uwAULVRpeP6hQSd2ZMv+C0q5J60XcdRDUwSNitbe"
    isProxy: true

#elastic-job配置
SERVER_LISTS: pd-zk-yz-01.brapp.com:2181,pd-zk-yz-02.brapp.com:2181,pd-zk-yz-03.brapp.com:2181
NAMESPACE: marketing-job
BASE_SLEEP_TIME_MILLISECONDS: 1000
MAX_SLEEP_TIME_MILLISECONDS: 3000
MAX_RETRIES: 3
NESTED_PORT: -1
NESTED_DATA_DIR: target/test_zk_data/
corn:
  taskJob: 0 0/30 * * * ?
# 雪花算法数据中心ID
snowflake:
  datacenter:
    id: ${SNOWFLAKE_DATACENTER_ID:0}
rocketmq:
  # 多个NameServer，host:port;host:port，RocketMQProperties
  name-server: ${ROCKET_NAME_SERVER:10.100.177.1:9875;10.100.177.2:9875;10.100.177.3:9875}
  producer:
    # 发送同一类消息的设置为同一个group，保证唯一
    group: Marketing_Default_Group
    # 发送消息失败重试次数，默认2
    retryTimesWhenSendFailed: 3
    # 异步消息重试此处，默认2
    retryTimesWhenSendAsyncFailed: 2
    # 发送消息超时时间，默认3000
    sendMessageTimeout: 5000
    # 消息最大长度，默认1024 * 1024 * 4(默认4M)
    maxMessageSize: 4194304
    # 压缩消息阈值，默认4k(1024 * 4)
    compressMessageBodyThreshold: 4096
    # 是否在内部发送失败时重试另一个broker，默认false
    retryNextServer: false
    # access-key
    #accessKey: xxx
    # secret-key
    #secretKey: xxx
    # 是否启用消息跟踪，默认false
    enableMsgTrace: false
    # 消息跟踪主题的名称值。如果不进行配置，可以使用默认的跟踪主题名称
    customizedTraceTopic: RMQ_SYS_TRACE_TOPIC
  consumer:
    #    # 配置指定group是否启动监听器 group1.topic1 = false
    #    listeners:
    #      # key：group名称
    #      rocketmq_source_code_group:
    #        # value：{key: topic名称: value: true/false}
    #        rocketmq_source_code: true
    # 指定消费组
    group: Marketing_Default_Group
    # 指定topic，启动时就会注册
    #topic: springboot_consumer_xxx
    # 一次拉取消息最大值，注意是拉取消息的最大值而非消费最大值
    pull-batch-size: 5
    # 其他配置参考属性类