datasource:
  database:
    names: shardingmarketing,marketing-tikiv,marketing-tiflash
    defaultSource: shardingmarketing
    shardingmarketing:
      name: shardingmarketing
      jdbc-url: jdbc:mysql://tidb-w-brsms.brapp.com:4000/loan_warning?useUnicode=true&characterEncoding=UTF-8&connectTimeout=3000&socketTimeout=300000&autoReconnect=false&failOverReadOnly=false&useConfigs=maxPerformance
      username: u_pd_l_warning
      password: pb4WgQCCY/pwIwe/6/HS
      type: com.zaxxer.hikari.HikariDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      minimum-idle: 1 # 最小空闲连接数
      maximum-pool-size: 300 # 最大连接池数量
      connection-timeout: 60000 # 获取连接超时时间，单位毫秒
      idle-timeout: 300000 # 连接空闲超时时间，单位毫秒
      max-lifetime: 1800000 # 连接最大生命周期，单位毫秒（30分钟）
      keepalive-time: 30000 # 连接保活时间，单位毫秒
      connection-test-query: select 1 # 连接测试查询
    marketing-tikiv:
      name: marketing-tikiv
      type: com.zaxxer.hikari.HikariDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://tidb-w-brsms.brapp.com:4000/loan_warning?useUnicode=true&characterEncoding=UTF-8&connectTimeout=3000&socketTimeout=300000&autoReconnect=false&failOverReadOnly=false&useConfigs=maxPerformance
      username: u_pd_l_warning
      password: pb4WgQCCY/pwIwe/6/HS
      minimum-idle: 5 # 最小空闲连接数
      maximum-pool-size: 30 # 最大连接池数量
      connection-timeout: 60000 # 获取连接超时时间，单位毫秒
      idle-timeout: 300000 # 连接空闲超时时间，单位毫秒
      max-lifetime: 1800000 # 连接最大生命周期，单位毫秒（30分钟）
      keepalive-time: 30000 # 连接保活时间，单位毫秒
      connection-test-query: select 1 # 连接测试查询
    marketing-tiflash:
      name: marketing-tiflash
      type: com.zaxxer.hikari.HikariDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://tidb-w-brsms.brapp.com:4020/loan_warning?useUnicode=true&characterEncoding=UTF-8&connectTimeout=3000&socketTimeout=300000&autoReconnect=false&failOverReadOnly=false&useConfigs=maxPerformance
      username: u_pd_l_warning
      password: pb4WgQCCY/pwIwe/6/HS
      minimum-idle: 4 # 最小空闲连接数
      maximum-pool-size: 4 # 最大连接池数量
      connection-timeout: 60000 # 获取连接超时时间，单位毫秒
      idle-timeout: 300000 # 连接空闲超时时间，单位毫秒
      max-lifetime: 1800000 # 连接最大生命周期，单位毫秒（30分钟）
      keepalive-time: 30000 # 连接保活时间，单位毫秒
      connection-test-query: select 1 # 连接测试查询
logging:
  level:
    com.br.off.mapper: debug
  file:
      name: ./logs/core.log
  root: INFO
otherConfig:
  huaXiangInterface:
    getReport: http://CLOUD-HX-RIBBON/huaxiang/v1/get_report
  sanxiangzhiliInterface:
    sanxiang_url: http://zh-service/v1/getData
    haina_url: http://HAINA-SERVICE/query
  alarm:
    secretKey: f72b7def3d3c5e2d93d4c0f3be664f21
    mails: xinke.liu@100credit.com,guang.chen@100credit.com,runtong.yuan@100credit.com
    appName: loan-warning
    outsideSecretKey: d4a52dd442b2983f499b05ec37c5b7f9
    outsideAppName: loan-warning-outside
  userCenter:
    appName: marketing-api
    appSecretKey: 77786bf195aa73044af33f8fce6c0441
  encodeMapping:
    appName: marketing
    appSecretKey: d37f90c97204a2ef3fe774fc5f106cf5
  warning:
    pageSize: 5000
    apiUrl: http://compass-api.100credit.com/api/loan-warning-api/loanStrategy/v2/query
    path: /opt/data/inloan/download/warning/
    ftpHost: 10.100.188.120
    ftpPort: 21
    ftpUsername: dev_web
    ftpPwd: 0tMKa8jf@8zg
    sftpHost: brsftp3.brapp.com
    sftpPort: 9999
    sftpUser: loan_warning
    sftpPwd: 2lT57nWUlel0FxkNDHlK@_2020.11.03
    email:
      notice: nengwu.qu@100credit.com,chunliu.le@100credit.com,qianqian.cao@100credit.com,xinke.liu@100credit.com

api:
  dass:
    baseUrl: http://testdaas.huiyunai.com
    postHermesUserData: ${api.dass.baseUrl}/csos-daas/call/postHermesUserData
    aeskey: MgoTm8GxuxTUc6y5
    SecretKey: MIICeAIBADANBgkqhkiG9w0BAQEFAASCAmIwggJeAgEAAoGBAKm7vv0ZdB36H8sGL2YZWAPM3sQ+tMbfoPp71KncNzOzMMqd9KiK9tPrfeoApo+xXBZFvid8f+1BxiyU7/bHrxiIFvawfzTt0PTj/gYcM9k0gMMUmomGNir9PMzV2WWBDpvSLUSoWX56yk3LhUB4rHXrj5pUIpO0pEr5b9cPQbZBAgMBAAECgYEAkSXIkdBuiCQZhBjp97m8lqNf7RpipZ8fnpS+q/NyEXgvRVYGnwsXQOqlZrLfvQnC4hkKH+JL06znt8A15SemB0NizbDmFvtsi+tQQm9qK8jvMkdo6zVeXlNjJ2kDVu98WFDK3EEukWTQXiYTdX6paKiFQnWQwV/EKlb/Bi3lfEECQQDclPdFCptoKDv52HEqs4UbsGY/yO4ZbZXTPst1w0EKjhFIn9jcoFPBoO3o4URPM8ENeBZv8bpU0djGO2nCfAGFAkEAxPymAEbUmtHH893JILrfo65O85K5MmGNR/NSdn4uBjD9E0R1cWB3SHlfDUv9+r0GtuQasLSp3cvJI5OY2sdgjQJBALmurHfx9eA3/kTTbnADrokgdPI8sjG1jenFcoAvXREFhoccB/GxBNB6J8th1Z7Wcixkan7RfYjpHRHB8cVFngECQFy0tn8s1oPiNKMtfql7qSKENz3kkGoIhRAWkHmZmplpVsFJl6f7CUg/bp94Yxgs+8r5ASKmc8chUBEBNo/IA0UCQQCt75iTugjsjbZUvoYHwZ9A7Bf7vfG7sOI3cismFzARUpSUPN6dEht4X4Z2AdC9HXXS+Mb3vFaCIK+h3WDZeZJt
  twoSeven:
    baseUrl: http://8.129.19.178:8888
    zhuangku: ${api.twoSeven.baseUrl}/zhuangku
    isProxy: 1
  marketing:
    baseUrl: http://k8s.brapp.com/compass-api/api/marketing-api
    transferUrl: ${api.marketing.baseUrl}/marketingTransferData/receiveTransferDataSync
    uploadUrl: ${api.marketing.baseUrl}/marketingUserPre/receiveMarketingPreUser
  zhongAn:
    baseUrl: https://finance-gateway-pop.diandian.com.cn
    api: ${api.zhongAn.baseUrl}/fcpGateway
    isProxy: true
    rsapKey: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCG0Brdms00ECe0Qo/Fljo1S/ZAjGe9BvhLAH9zCGpeQLI9opkvyZFSnBhdP+Nb1pFPQkls8Dpsr0J17M8uEcoglIK1ADVxnqOf9qbzwgDE44/6Bca28gid+b1aL2KpWc0B1U/Q/TFn7ez93/jGcDXN5wxErR2+sIUE1oRUuZQC9wIDAQAB
    xdCode: 07brdyy001
    bxCode: 3360001
  didi:
    baseUrl: https://admarketing-manhattan.xiaojukeji.com
    smsUrl: ${api.didi.baseUrl}/crow/collision/bairong
    reachUrl: ${api.didi.baseUrl}/crow/user/success/bairong
    jmassSUrl: ${api.didi.baseUrl}/model/sample/bairong
    failedUrl: ${api.didi.baseUrl}/crow/faileduser/mediaName
    token: DK&SgWl!fZ%WVSXe
    scas: "0001"
    channelId: 3140738836439875
    channelIdMap: "{bairong:'3140738836439875',bairongA:'3140738898634899'}"
    isProxy: true
  qifu:
    baseUri: https://gws-bps.daikuan.360.cn
    saveReachDeleteRecordUrl: ${api.qifu.baseUri}/api/gws/bps/gateway/agent/operation/agentOperationSaveReachDeleteRecord
    qifuPublicKey: ""
    brPrivateKey: ""
    brPublicKey: ""
    isProxy: true
  tongchengAgentMkt:
    baseUrl: https://mns.lylend.com
    address: ${api.tongchengAgentMkt.baseUrl}/api/cep/agent/mkt/baiRong
    secretKey: 3VMUkXxpauLzA7kzHdq7uCNMFjDUMCgyUzgSe83hdb64QcU2KJT5Rcb7enVtYzR9
    isProxy: true
innerSftp:
  uploadpath: /UploadFiles/marketing/
#elastic-job配置
SERVER_LISTS: pd-zk-yz-01.brapp.com:2181,pd-zk-yz-02.brapp.com:2181,pd-zk-yz-03.brapp.com:2181
NAMESPACE: marketing-job
BASE_SLEEP_TIME_MILLISECONDS: 1000
MAX_SLEEP_TIME_MILLISECONDS: 3000
MAX_RETRIES: 3
NESTED_PORT: -1
NESTED_DATA_DIR: target/test_zk_data/
