#默认值false
speed.enable.remote.conf=true
#获取远程配置信息的服务器主机名
#speed.conf_server_host=speed-proxy.brapp.com
speed.k8s_service_name=speed-proxy-service
#应用名，必须填写否则抛异常
speed.app=marketing-check
#主题名，必须填写否则抛异常
speed.topic=marketing
#获取配置文件秘钥，必须填写否则抛异常
speed.sim.secretkey=6bad4826dd017c9ffc19ee96a8c0af24
speed.prod.secretkey=1d9f22b3b2a5591f904d6156803e982b
#环境:test,pre,sim,prod
#speed.env=sim
#忽略托管的配置名
#speed.ignore
#获取远程配置的重试次数(建议该配置大于等于3,防止网络不稳定等因素获取失败,)
speed.conf_server_url_retry_times=3
#重试时间间隔
speed.conf_server_url_retry_sleep_seconds=1
#远程下载文件的本地下载存储路径
speed.user_define_download_dir=/opt/data/marketing
#是否将配置文件考拷贝到classpath路径下
speed.enable_local_download_dir_in_class_path=true