sharding:
  jdbc:
    datasource:
      names: shardingmarketing
      shardingmarketing:
         name: shardingmarketing
         jdbc-url: jdbc:mysql://tidb-pre.brapp.com:4000/marketing?useUnicode=true&characterEncoding=UTF-8&connectTimeout=3000&socketTimeout=300000&autoReconnect=false&failOverReadOnly=false&useConfigs=maxPerformance
         username: ENC(mysql-pre-ai-marketing-user)
         password: ENC(mysql-pre-ai-marketing-password)
         type: com.zaxxer.hikari.HikariDataSource
         driver-class-name: com.mysql.cj.jdbc.Driver
         minimum-idle: 1 # 最小空闲连接数
         maximum-pool-size: 300 # 最大连接池数量
         connection-timeout: 60000 # 获取连接超时时间，单位毫秒
         idle-timeout: 300000 # 连接空闲超时时间，单位毫秒
         max-lifetime: 1800000 # 连接最大生命周期，单位毫秒（30分钟）
         keepalive-time: 30000 # 连接保活时间，单位毫秒
         connection-test-query: select 1 # 连接测试查询
    config:
      sharding:
        props:
          sql.show: false
        tables:
          b_marketing_user:
            table-strategy:
              inline:
                sharding-column: api_code
                algorithm-expression: b_marketing_user_${api_code}
logging:
    level:
        com.br.off.mapper: debug
    file:
      name: ./logs/core.log
    root: INFO
otherConfig:
  alarm:
        secretKey: a9c57e4138807a9e18b439cd9dab275b
        appName: marketing
        outsideSecretKey: 71e63ead0af0a07ae4191eb14b75a541
        outsideAppName: marketing-out
  userCenter:
    appName: marketing-api
    appSecretKey: bd3c18667f8fcbb4985d2be66e70ca1e
  encodeMapping:
    appName: marketing
    appSecretKey: c6acc38a39b0769fa7fb1a95f82d9b33
  warning:
        pageSize: 5000
        apiUrl: http://compass-api.100credit.com/api/loan-warning-api/loanStrategy/v2/query
minio:
  endpoint: http://10.100.123.246:9000
  accessKey: dA1IO0IMNKqmJYqOlEWv
  secretKey: oDvwsAeIah122STixfF0OXZHMQhHsKzWvQMk7FbO
  bucketName: brmarketing-pre

cluster:
  flag: ${CONF_CLUSTER}
#elastic-job配置
SERVER_LISTS: speed-zk-01.brapp.com:2181,speed-zk-02.brapp.com:2181,speed-zk-03.brapp.com:2181
NAMESPACE: marketing-job-default
BASE_SLEEP_TIME_MILLISECONDS: 1000
MAX_SLEEP_TIME_MILLISECONDS: 3000
MAX_RETRIES: 3
NESTED_PORT: -1
NESTED_DATA_DIR: target/test_zk_data/

rocketmq:
  # 多个NameServer，host:port;host:port，RocketMQProperties
  name-server: 10.100.123.171:9876;10.100.123.172:9876;10.100.123.173:9876
  producer:
    # 发送同一类消息的设置为同一个group，保证唯一
    group: Marketing_Default_Group
    # 发送消息失败重试次数，默认2
    retryTimesWhenSendFailed: 3
    # 异步消息重试此处，默认2
    retryTimesWhenSendAsyncFailed: 2
    # 发送消息超时时间，默认3000
    sendMessageTimeout: 5000
    # 消息最大长度，默认1024 * 1024 * 4(默认4M)
    maxMessageSize: 4194304
    # 压缩消息阈值，默认4k(1024 * 4)
    compressMessageBodyThreshold: 4096
    # 是否在内部发送失败时重试另一个broker，默认false
    retryNextServer: false
    # access-key
    #accessKey: xxx
    # secret-key
    #secretKey: xxx
    # 是否启用消息跟踪，默认false
    enableMsgTrace: false
    # 消息跟踪主题的名称值。如果不进行配置，可以使用默认的跟踪主题名称
    customizedTraceTopic: RMQ_SYS_TRACE_TOPIC
    namespace: ${ROCKETMQ_NAMESPACE:pre_istio}
  consumer:
#    # 配置指定group是否启动监听器 group1.topic1 = false
#    listeners:
#      # key：group名称
#      rocketmq_source_code_group:
#        # value：{key: topic名称: value: true/false}
#        rocketmq_source_code: true
    # 指定消费组
    group: Marketing_Default_Group
    # 指定topic，启动时就会注册
    #topic: springboot_consumer_xxx
    # 一次拉取消息最大值，注意是拉取消息的最大值而非消费最大值
    pull-batch-size: 5
    # 其他配置参考属性类
    namespace: ${ROCKETMQ_NAMESPACE:pre_istio}