#默认值false
speed.enable.remote.conf=true
#svc方式访问配置中心代理服务
speed.conf_server_host=speed-proxy-pre.brapp.com
#应用名，必须填写否则抛异常
speed.app=marketing-xc-consumer
#主题名，必须填写否则抛异常
speed.topic=marketing
#获取配置文件秘钥，必须填写否则抛异常
speed.pre.secretkey=848ec6e4a4b486d82367d62adbc09ca1
#环境:test,pre,sim,prod
speed.env=pre
#忽略托管的配置名
#speed.ignore
#获取远程配置的重试次数(建议该配置大于等于3,防止网络不稳定等因素获取失败,)
speed.conf_server_url_retry_times=3
#重试时间间隔
speed.conf_server_url_retry_sleep_seconds=1
#远程下载文件的本地下载存储路径
speed.user_define_download_dir=/opt/data/marketing
#是否将配置文件考拷贝到classpath路径下
speed.enable_local_download_dir_in_class_path=true