#客户端参数配置
#单个服务service的channel管道，缺省值：4,最大不超过8，超过8强制为8个管道
grpc.channal.num=4
#负载均衡两种方式：pick_first/round_robin  默认：pick_first.channel会根据负载均衡策略生成对应的subchannel,建议使用：round_robin负载，另外istio集群内是通过istio本身负载机制实现，该项不起作用
grpc.balance_proxy=round_robin
#service_config策略:default/service_config.json。如果配置default，默认服务配置策略（无重试，无超时等）。建议：业务自己实现重试
grpc.service_config=default
# 空闲时间，单位分钟，默认30。istio中因为envoy代理无用，不用更改
grpc.idle.timeout=
#最大流入流量大小：单位Mb。一般有用，无需更改，如果涉及大消息体业务自己根据需求评估
grpc.max.inbound.message.size=32
#meta 大小，单位：kb。一般够用，无需更改
grpc.max.inbound.metadata.size=8
#keepalive ping 发送周期间隔：单位s。  默认9223372036854776000 纳秒。istio中因为envoy代理无用，不用更改
grpc.keepalive.time=
#确认keepalive ping等待发送返回的时间：单位s，超过断开。底层默认20s。istio中因为envoy代理无用，不用更改
grpc.keepalive.timeout=
#没有请求的时候是否允许发送keepalive ping。默认false。istio中因为envoy代理无用，不用更改
grpc.keepalive.without.calls=false
# deadline:绝对超时时间，单位s,每次stub调用的请求超时时间，通过stub进行设置。业务根据自己场景适当调整
grpc.deadline.time=3
#消息压缩:a)值为空默认不压缩;b) 值为gzip，标识对消息进行gzip压缩，如果消息体比较大，需要开启对应gzip压缩。业务根据自己场景适当调整
grpc.message.compresss=
#是否开启客户端拦截监控，需要自己配置监控拦截参数，建议：true。业务自己dashboard可以增加grpc client的监控，找运维配置
grpc.client.monitor=true
#客户端启动核心线程数，默认缺省值为20。业务根据自己请求评估,注意该参数为单个channel的线程连接，如果客户端channel个数为4,则有20*4=80个核心线程,所以请合理设置，建议设置8
grpc.client.executor.thread.min=8
#客户端启动最大线程数，默认缺省值为100。业务根据自己请求评估,注意该参数为单个channel的线程连接，如果客户端channel个数为4，则有100*4=400个最大线程，所以请合理设置，建议设置20
grpc.client.executor.thread.max=20
#客户端采用ArrayBlockingQueue，该值为该队列大小，默认缺省值为800，业务根据自己请求评估
grpc.client.executor.queue.size=800
