#推送客服的apicode  七七,数禾,海尔,榕树,玖富
apiCodeOfpushCustomer=["4004643","3710004","3710030","7410437","7410780","7410794","7410797","7410785","7412002","3710034","7410787"]
#推送哈啰的apicode
apiCodeOfpushHaluoByTransfer=["3710028"]
#是否是标准客服转化接口
customerTransferIsYx={"3710012":true,"7410787":true}
#海尔apicode
haierApiCode=["3710018","7410930"]
#玖富apicode
jfApiCode=["7412002","3710034"]
#记录taskid时间的apicode
apiCodeOfRecordTaskTime=["3710028","7410437","7410850"]
#去重线程数
soleNum=10
#萨摩耶场景转化需要判断的场景
groupTypeSaMoye=["S01","S02","S0202","S04","S06","S08"]
#数禾apicode
shuheApiCode=["3710004","7410785"]
#通用转化流程
universalProcessApiCode=["7412003","3710012","7410930","3710018","3710045","7492631","7492632","3710014","3710015","3710043","3710022","7412100","7410850","3710028","3710033","7492634","7410820","3710037","7410785","7410875","3710023","3710071","3710004","3710051","7410951"]
#规则匹配映射
customerRuleMapping={"7412003":"YiXin","3710012":"YiXin","3710045":"YiXin","7410930":"Haier","3710018":"Haier","7410785":"ShuHe","3710004":"ShuHe","3710023":"ShuHe"}
# 数禾转化数据提取分场景, T 代表当前天到月底； T+/-day 代表当前天到day天;
## eg：{"促首登":"T","促申完":"T-15","促首借":"T+31","促复借":"T+0"}
shuHeTransferExtractDayMap={"促首登":"T+31","促申完":"T+15","促首借":"T+34","促复借":"T+31","重申":"T+31"}
# 数禾转化数据提取apiCode集合
shuHeTransferExtractApiCodes={"3710004":["促申完","促首登"],"3710023":["促首借"],"7410785":["促申完","促首登","促首借","促复借","重申"],"3710043":["促复借"],"3710051":["重申"],"7412008":["重申"],"3710071":["促首登"]}
# 数禾转化数据提取任务开始时间
shuHeTransferExtractJobStartTime=06:00:00
# 数禾转化数据提取任务是否使用准全量转化数据
shuHeTransferExtractIfUseQuasiTotalQuantity=true
# 数禾有效期, T 代表当前天到月底； T+/-day 代表当前天到day天;
## eg：{"促首登":"T","促申完":"T-15","促首借":"T+31","促复借":"T+0"}
shuHePeriodOfValidityDayMap={"促首登":"T+31","促申完":"T+15","促首借":"T+34","促复借":"T+31","重申":"T+31"}
#消息队列过期时间
messageQueueExpireTime=3600000
#宜信实时转化数据提取apiCode集合
yinXinTransferRealTimeApiCodes=["3710012","7410787"]
#宜信实时转化数据提取Job执行时间
yinXinTransferRealTimeExecuteTime=20:00:00
#宜信通用流程使用apiCode
yiXinApiCode=["7412003","3710012","3710045"]
#电销文件定制处理集合
dxFileCustomize={"yixin":["3710012"],"xw":["4004666","7412003"],"juzi":["123"]}
#宜信非实时typelist
yixinNoRealTimeType=["13","9","7","17","18","6","8","4","15"]
#宜信非实时推客服typelist
yixinNoRealTimePushRobotAIType=["4","5","6","7","8","11","12","14","15","17","18","19"]
#宜信非实时转化数据提取Job执行时间
yinXinTransferNoRealTimeExecuteTime=12:00:00
#是否开启宜信非实时数据提取
isOpenYinXinTransferNoRealTimeExtract=true
#拍拍贷客户apiCode
ppdCustomerType={"lend":["3710015","7492632"],"transform":["3710014","7492631"]}
#促复借可用额度
clcUsrAvlLmtLv0=100
# 数禾推送电销情况;eg:{"促复借":["a","b","c"],"促首借":["a","b"]}
shuHePushDXStatusMap={"促复借":["a","b"]}
# 数禾用户可用额度区间;大于:&gt;、小于:&lt;、等于:&eq;、不等于:&nq;、大于等于:&ge;、小于等于:&le;;eg:["&ge;","1","&le;","100"]
shuHeUserAvailableQuotaRange=["&ge;","100"]
# 拨打记录数据配置apicode推送mq
callRecordDataPushMqApiCodes=["3710004","3710023","3710043","7410785","7410906","3710048","7410950","7410951","3710058"]
#玖富转化数据提取apiCode集合
JiuFuTransferApiCodes=["3710034","7412002"]
#玖富转化数据提取执行时间
JiuFuTransferExecuteTime=10:00:00
#哈啰拨打回调数据落库线程数
haloSaveDataThreadNum=50
# 小赢转化数据推送智能客服apiCode集合
xiaoYingTransferPushRobotApiCodes=["3710022","7412100"]
# 小赢转化数据提取apiCode集合
xiaoYingTransferExtractApiCodes=["3710022","7412100"]
# 小赢登录断点转化数据提取任务开始时间
xiaoYingDengLuDuanDianTransferExtractJobTime=10:00:00
# 小赢促提转化数据提取任务开始时间
xiaoYingCuTiTransferExtractJobTime=10:00:00
#小赢全量转化数据提取任务开始时间
xiaoYingFullLoadTransferExtractJobTime=10:00:00
#数禾推送电销人工黑名单过滤天数和推送客服黑名单有效截至天数
shuhePushBlackDay={"dassBlack":30,"customerBlack":30}
#哈罗转化数据规则
haluoTransferRule={"status":"a,b,d","Ddate":"5","ABCdate":"5","taskIddate":"35","dTimes":"7"}
#sql执行选择数据源配置
sqlType={"buildTaskNum":1,"scoreMinId":0,"scoreData":0}
#跑分线程资源数量
taskResourceMaxNum=400
#拍拍贷新客实时转化数据提取apiCode集合
PPDTransferFileApiCodes=["3710014"]
#拍拍贷新客实时转化数据提取执行时间
PPDTransferFileExecuteTime=10:00:00
#宜信实时转化数据real-pass执行时间
yinXinTransferRealPassExecuteTime=12:00:00
#check服务job的上线开关
checkJobOnlineSwitch=false
#离线文件入es线程数量
OffLineInserEsThreadNum=50
#同程金融转化有效期,T代表当前天到月底,T+/-day代表当前天到day天
tongChengPeriodOfValidityDay=T+30
#原始数据流转至规则的apicode集合
initDataPushRule=["7410437","4004713","4004714"]
#原始数据推送决策手机号加密类型 1-md5;2-sha256
pushCellEncPolicy={"7410437":1,"4004713":1,"4004714":1}
#同程转化数据提取apicode集合
tongChengTransferFileApiCodes=["3710062","7492634"]
#同程转化数据提取执行时间
tongChengTransferExecuteTime=08:00:00
#自由定义场景与上传日期，其中key userType；value dateSet
freeUserTypeAndDateMap={"A":["2022-05-27"],"B":["2022-05-27"],"4":["2022-01-18"],"5":["2022-01-19"],"6":["2022-01-20"],"11":["2022-01-25"],"1":["2022-01-15"],"2":["2022-01-16"],"3":["2022-01-17"],"7":["2022-01-21"],"8":["2022-01-22"],"9":["2022-01-23"],"10":["2022-01-24"]}
#nfs路径
nfsPath=/opt/data/inloan/download/marketing/
#海尔有效期，T代表当天,T+day代表day天到当天
haierPeriodOfValidityDay=T+40
#桔子转化数据入库特殊处理apicode集合
juZiTransferInsertApiCodes=["7410820","3710037"]
#哈啰转化数据提取apicode集合
haLuoTransferFileApiCodes=["3710028"]
#萨摩耶转化数据提取apicode集合
saMoYeTransferFileApiCodes=["3710013"]
#桔子周期性推送dass,查询实时推送数据日期;eg:{"a":[2],"b":[2],"c":[2,6,13,27],"d":[6]}
orangeTransferCyclicalPushDassDay={"a":[2],"b":[2],"c":[2,6,13,27],"d":[6]}
#桔子实时转化定时任务执行时间
juZiRealTimeTransferExecuteTime=10:30:00
#桔子实时转化锁定期配置
juZiRealTimeLockConfig={"applyDt":"30","applyLoanTime":"30","lentTime":"30","pushNum":"6"}
#众安名单锁定推送数据线有效期, T 代表当前天到月底； T+/-day 代表当前天到day-1天，共day天
zhongAnPeriodOfValidityDay={"7410906":"T+15","3710048":"T+37"}
#众安名单锁定推送数据线程池配置,eg：[25,50],25为核心线程数，50为最大线程数
zhongAnPushTreadPoolSize=[10,10]
#众安名单锁定推送数据线程池配置,eg：{"CG":[50,100],"MG":[50,100],"other":[1,20]},50为业务线程数据，100为推送线程数
zhongAnPushTreadPoolSizeMap={"CG":[50,100],"MG":[50,100],"other":[1,20]}
#众安推送锁定名单推送时间
zhongAnRosterLockingTime=21:00
#众安推送黑名单定时任务开关：true 打开，false 关闭执行
zhongAnPushBlackDataSwitch=true
#众安推送黑名单定时任务执行时间
zhongAnPushBlackDataExecuteTime=00:00:00
#众安推送黑名单线程数设置
zhongAnPushBlackThreadNum=200
#众安推送黑名单数据有效期
zhongAnPushBlackDataPeriod=36
#接口日志记录判断标识key为接口名称，第一个为db记录判断，第二为file记录判断{"zanPushDetail":[false,true],"zanZk":[false,true]}
apiLogMark={"zanPushDetail":[false,true],"zanZk":[false,true],"xieChengSmsQuit":[false,true]}
#推送决策优化跑分记录时间节点
scoreFileYhTime=2022-12-01 17:00:00
#跑分分组分位值
quantileValue=50000000
#规则筛选从es获取的最大线程数
scoreByEsThreadNum=10
#规则筛选调用决策接口的线程数
scoreToJcThreadNum=5
#携程转化数据入库特殊处理apicode集合
xieChengTransferInsertApiCodes=["7410951"]
#众安异业撞库数据提取apiCode集合
ZhongAnTransferApiCodes=["3710048","7410908"]
#众安异业撞库数据提取执行时间
ZhongAnTransferExecuteTime=10:00:00
#携程转化数据提取apiCode集合
XieChengTransferApiCodes=["3710058","7410951"]
#携程转化数据提取执行时间
XieChengTransferExecuteTime=09:00:00
#携程推送数据线程池线程数量
xiechengDataSendThread=50
#拍拍贷老客转人工数据提取执行时间
PPDOldTransferFileExecuteTime=11:00:00
#拍拍贷老客转人工数据提取apiCode集合
PPDOldTransferFileApiCodes=["3710015","7492641"]
#拍拍贷有效期34；目前仅老客使用
ppdOldValidityDayStr=[T+33]
#拍拍贷老客推电销去重时间天数
ppdOldPhoneValidityDay=5
#桔子转化数据提取
orangeTransferFileApiCodes=["7410821","3710075"]
#分期乐自动化周期转决策周期，day为周期天数，格式{apiCode:{day:策略编号}}
fenqilePeriodPushDecisionPeriod={"3710027":{0:"CASTR0000361",7:"CASTR0000362",14:"CASTR0000363"},"7433900":{0:"CASTR0000851",7:"CASTR0000853",14:"CASTR0000854"}}
#自动化转决策任务配置 key {@link CustomerPushDecisionActionEnum}; value List{@link JobPushDecisionParameterBO}
jobPushDecisionParameterMap={"ZHONG_AN":[{"apiCode":"3710048","timeStr":"09:00:00","paramMap":{"1":"a","2":"b"}},{"apiCode":"7410906","timeStr":"09:00:00","paramMap":{"1":"a","2":"b"}}]}
#永辉化数据提取apiCode
yonghuiTransferExtractApiCodes=["3710082","7492900"]
#永辉转化数据提取时间
yonghuiTransferExtractTime=11:00
#非生成默认有效期配置的apiCode集合
nonConfigValidDefaultApiCodes=["7410908"]
#众邦状态分组与开关，状态优先级与配置顺序对应，最先配置的优先级也最高,d为状态；groupNumber为组号；dxUserType为人工电销业务线场景；switch为开关标识，true为开
zhongbangStatusTypeMap={"d":{"groupNo":2,"dxUserType":"2","switch":true},"c":{"groupNo":1,"dxUserType":"1","switch":true},"b":{"groupNo":1,"dxUserType":"1","switch":true},"a":{"groupNo":1,"dxUserType":"1","switch":true}}
#众邦手机去重天数，默认7天
zhongbangCellDistributeDay=7
#众邦转化数据推送daas线程数,默认1
zhongBangTransferPushDaasThreadPoolSize=1
#奇富接口公钥
qiFuApiPublicKey=
#奇富接口AppId
qiFuApiAppId=bairong
#客户定制化接口自定义配置apiCode eg:{"T_GUME":["3710076", "7492805"]}
customerHandlerEnumConfigMap={"T_GUME":["3710076", "7492805"]}