datasource:
  database:
    names: shardingmarketing,marketing-tikiv,marketing-tiflash,marketing-log
    defaultSource: shardingmarketing
    shardingmarketing:
      name: shardingmarketing
      jdbc-url: jdbc:mysql://tidb-pre.brapp.com:4000/marketing?useUnicode=true&characterEncoding=UTF-8&connectTimeout=3000&socketTimeout=300000&autoReconnect=false&failOverReadOnly=false&useConfigs=maxPerformance
      username: ENC(mysql-pre-ai-marketing-user)
      password: ENC(mysql-pre-ai-marketing-password)
      type: com.zaxxer.hikari.HikariDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      minimum-idle: 1 # 最小空闲连接数
      maximum-pool-size: 300 # 最大连接池数量
      connection-timeout: 60000 # 获取连接超时时间，单位毫秒
      idle-timeout: 300000 # 连接空闲超时时间，单位毫秒
      max-lifetime: 1800000 # 连接最大生命周期，单位毫秒（30分钟）
      keepalive-time: 30000 # 连接保活时间，单位毫秒
      connection-test-query: select 1 # 连接测试查询
    marketing-tikiv:
      name: marketing-tikiv
      type: com.zaxxer.hikari.HikariDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://tidb-pre.brapp.com:4000/marketing?useUnicode=true&characterEncoding=UTF-8&connectTimeout=3000&socketTimeout=300000&autoReconnect=false&failOverReadOnly=false&useConfigs=maxPerformance
      username: ENC(mysql-pre-ai-marketing-user)
      password: ENC(mysql-pre-ai-marketing-password)
      minimum-idle: 5 # 最小空闲连接数
      maximum-pool-size: 30 # 最大连接池数量
      connection-timeout: 60000 # 获取连接超时时间，单位毫秒
      idle-timeout: 300000 # 连接空闲超时时间，单位毫秒
      max-lifetime: 1800000 # 连接最大生命周期，单位毫秒（30分钟）
      keepalive-time: 30000 # 连接保活时间，单位毫秒
      connection-test-query: select 1 # 连接测试查询
    #      removeAbandoned: true # 是否自动回收超时连接
    #      removeAbandonedTimeout: 1800 # 超时时间(以秒数为单位)
    #      filters: stat,wall,log4j2
    #      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    marketing-tiflash:
      name: marketing-tiflash
      type: com.zaxxer.hikari.HikariDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://tidb-pre.brapp.com:4020/marketing?useUnicode=true&characterEncoding=UTF-8&connectTimeout=3000&socketTimeout=300000&autoReconnect=false&failOverReadOnly=false&useConfigs=maxPerformance
      username: ENC(mysql-pre-ai-marketing-user)
      password: ENC(mysql-pre-ai-marketing-password)
      minimum-idle: 4 # 最小空闲连接数
      maximum-pool-size: 4 # 最大连接池数量
      connection-timeout: 60000 # 获取连接超时时间，单位毫秒
      idle-timeout: 300000 # 连接空闲超时时间，单位毫秒
      max-lifetime: 1800000 # 连接最大生命周期，单位毫秒（30分钟）
      keepalive-time: 30000 # 连接保活时间，单位毫秒
      connection-test-query: select 1 # 连接测试查询
#      removeAbandoned: true # 是否自动回收超时连接
#      removeAbandonedTimeout: 1800 # 超时时间(以秒数为单位)
#      filters: stat,wall,log4j2
#      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    marketing-log:
      name: marketing-log
      type: com.zaxxer.hikari.HikariDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://tidb-pre.brapp.com:4000/marketing_log?useUnicode=true&characterEncoding=UTF-8&connectTimeout=3000&socketTimeout=300000&autoReconnect=false&failOverReadOnly=false&useConfigs=maxPerformance
      username: ENC(mysql-pre-ai-marketing-log-user)
      password: ENC(mysql-pre-ai-marketing-log-password)
      minimum-idle: 5 # 最小空闲连接数
      maximum-pool-size: 30 # 最大连接池数量
      connection-timeout: 60000 # 获取连接超时时间，单位毫秒
      idle-timeout: 300000 # 连接空闲超时时间，单位毫秒
      max-lifetime: 1800000 # 连接最大生命周期，单位毫秒（30分钟）
      keepalive-time: 30000 # 连接保活时间，单位毫秒
      connection-test-query: select 1 # 连接测试查询

logging:
  level:
    com.br.off.mapper: debug
  file:
      name: ./logs/core.log
  root: INFO
otherConfig:
  alarm:
    secretKey: a9c57e4138807a9e18b439cd9dab275b
    appName: marketing
    outsideSecretKey: 71e63ead0af0a07ae4191eb14b75a541
    outsideAppName: marketing-out
  userCenter:
    appName: marketing-api
    appSecretKey: bd3c18667f8fcbb4985d2be66e70ca1e
  encodeMapping:
    appName: marketing
    appSecretKey: c6acc38a39b0769fa7fb1a95f82d9b33
  warning:
    pageSize: 5000
    apiUrl: http://compass-api.100credit.com/api/loan-warning-api/loanStrategy/v2/query
    path: /opt/data/inloan/download/marketing/
    sftpHost: 10.100.123.65
    sftpPort: 9999
    sftpUser: BRmarketing_pre
    sftpPwd: 72aXd79ITcMeuyPAlDYy@_2021.06.07
  proxy:
    proxy_host: squid-proxy-pre.brapp.com
    proxy_port: 3128
    proxy_username: spmarketing
    proxy_password: ek1EIgo9
    proxy_host_zw: 10.100.123.221
  mom:
    appSecretKey: d42726322ba9bda57b74043be21aa2c4
    appName: marketing_query_producer
    destinationName: marketing_query_log
api:
  xiecheng:
    openUrl: https://cgcallback-fat.ctripqa.com/nemoweb/ad/common/outAdMonitor.do
    appId: bairong001
    appIdVt: test002
    keyVt: 6b219b9e71fdb2d2
    ivVt: 5e7b6c07d3edbc01
    signKeyVt: b8845b4cb1f16471
    key: f3df6f62f0527bf0
    iv: 3b2dac323465b024
    singKey: 95cc01ec07387a44
    source: BaiRong_C01
    channel: commonOutAdMonitor
    isProxy: true
    smsQuit:
      openUrl: https://cgcallback-fat.ctripqa.com/nemoweb/ad/common/saveAdMobileBlack.do
      appId: test001
      key: 6b219b9e71fdb2d2
      iv: 5e7b6c07d3edbc01
      singKey: b8845b4cb1f16471
      channel: saveAdMobileBlack
      isProxy: true
    smsColliding:
      openUrl: https://cgcallback-fat.ctripqa.com/nemoweb/ad/common/unionCheckUser.do
      appId: bairong001
      appIdVt: test002
      keyVt: 6b219b9e71fdb2d2
      ivVt: 5e7b6c07d3edbc01
      signKeyVt: b8845b4cb1f16471
      key: f3df6f62f0527bf0
      iv: 3b2dac323465b024
      singKey: 95cc01ec07387a44
      channel: commonUnionCheckUser
      isProxy: true
  zhongyou:
    baseUrl: https://alissl.youcash.com/facadeuat/outmarketing-fileserver/file/out
    query: ${api.zhongyou.baseUrl}/query
    download: ${api.zhongyou.baseUrl}/download
    keyAlgorithm: RSA
    signAlgorithms: SHA1WithRSA
    aesKey: 3nbkz1h7kg7mueaq
    aesIv: hfhogkpfypizg2gi
    channelCode: BRYXkHIAvr0m2U0T
    rsaPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAhnl5uzpi0XZ2LIlc0C7kLe9JQ3v9els+K7WcsgRRrtszGCae6ko48NHf8xJvr8tWZqJf3P1YDzQe86pff9x7u6Xx4XqCbYIaH/DDsoXaZG+gvRtlRLDq5rXwncGFvx7lXAE/dOfyvK2OW7/bWbA9iZ5Za4mWKr3qwSHwOEptd93KPsvi5Xk0I8hcfik9BnTPds/P9nGNesHKk9E+Rt2GnPxa8h9aF8jFweie4MlaXzb3CkrM7vEaQZA+mwPTKvvYdCd20rIJmKwUMdG/k/KA80x3l6XwC5QCpa82AoBFVvUJyCXkxG9VRJ9q2nawLMiq6sES5Lq6sYIvu2O+b/z0DQIDAQAB
    rsaPrivateKey: MIIBVAIBADANBgkqhkiG9w0BAQEFAASCAT4wggE6AgEAAkEAr1BcLtKFLRQ92jl9mS4DyMyMOgYf0EZfmhE0R5WGs92XstydpUr8xVN5pwYkU3RNeKzNjXMR3K4aBksoren2mwIDAQABAkBc3ogGsbSkva1KVdwn8g1FKL472pStwynPtr9oEFisHJ024o7CJSHq6tqThFmNNg2vH9R1anILVC5JgfeRsWSBAiEA2t8fKnx5D41rywHyoSCBxhbokBS8qmO5O9PzSgEVPEECIQDNDavQZ5wTE151HkRXjlt12G5b+b/PVe3FC+p6MYCr2wIhAJ3/3/G9tW7iumPsXgiu/L/RHcWVErU2FCv6T3Cm43uBAiB37kYOh3r+oTZ+86vvNeEChQrPGrz4DH8b38NNosRqPwIgW8lPWHq4OlsW1G/KojSjigkRUtu2BEk+GJxW/aIYOrY=
    isProxy: true
  qifu:
    baseUri: https://stg1-gws-bps-web.daikuan.360.cn
    saveReachDeleteRecordUrl: ${api.qifu.baseUri}/api/gws/bps/gateway/agent/operation/agentOperationSaveReachDeleteRecord
    qifuPublicKey: "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAwQAaMvE6+7Wy+rf6jfW8OEKhGSmmg6LaiSLaTui3lBA4V4eqfQEpLfL8dGYYcakiH6CUAMPZ0jqNEN/En3Mtfclhr8903m/xG3IOUxhbqiVZBZmQ8esG6nP8MHsFWK2hMHN20xh0qKN6hg0BHQIIkbbnZjN9FGD/hz1t4NJvwIHxqJC+I3pRkCrC+SPWH5djzQdhYczgpyGwNqrGpg5dPibZJ+/qw15Va0vDBMp8cGad+Njcw5n7QcxBvSpViTYl704+wyohX36bF1CkrtfV6z1JnDqR+9KtEaRpfnUC/eh7gvltDbl/vTfeZLuShLs+/csgVshVIXEpL8g9uC0XOQIDAQAB"
    brPrivateKey: "MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQDdAO5CXKe5ugLICKdPeAXE7/4V484BPYdZVMoexCoWN7vwFV1dW8AyjsOYvvMOYSd/MOCqE0sK4CN/Tf857nalMqA5oU+MIEUkbb+KyXFXpNFi/LLi8FGGHQgTQFAS+Tikz1sHtYg3W8G7wQJsTDKXGQ7dEH9pJv3RbGZzQnTlzj/1brJ8uDGXYmKVPr2MbuOmtzCzzd9O0cPO1fEVwpnJbAUfQxZleMUL21OpkmTjqIBQfANf/24DjbJelZjRUA7YIR42XpxGXWeOlXR1D3jzIN0lguacwy+en3JvhbC62E6f04rzqs3TThlKxH4cjFZjOPvoGml2Z43S1k46lPjtAgMBAAECggEBANTyjKFM/iArZ3qvO+eK0qRMSxt0gY8YZk5hMNAsXBFEasaPD4NhYPRWM4n+k9yLKK+ZvSCjrm8wQYPs97wuVgwfl9tv32I5xeWwChwEtj2pBkjHDOc2gJclah6CnaVqlnXXhvMKq9ILi8UJ2PfZA/YrovLHbr03YOJl/OGaa2DxbIyDQsz8LH/4o7QLaRkAkwZw3egd/jepSB9hZwZ8NghkpqbSnRokjH+Rfx9b8uQ/MIqIfDXD8gMCALV+JFjG60mP/yGYS9xb1pHiW07M3QphYo8IV+X1YCnJ1nt7FrAQaPUIe+/zJhFsBM7EN6hX4RdqTacnpKZ0IfEOn/jU9YECgYEA9DLxbNPaAm5HnBA0tD7euFokyP9td8+EVhjeMPCZqPlVnWDm3c9bdrAWQbtwyMA0gvkcELtgFnPf0ICuV2FCKaTPtPa6C73ZR5ElBWkJ/pSbyYw8YGvN98Nh8xbEVqippN5Ypp8vQrZAT5A/qoekq0kYTS7Ymgqj7pq3xIPfHUUCgYEA568H8/qyhmrna84pAQf9gz3ln6EQWm/RfdOi+v42ZdL6sjmpHfT0VYaBuxc54D6OvhvPSoYizhZaHLuDnioaGwkDgducA057EIumDgn2Fvw1mUfcKymGngk4Z5GiWsFqJ66yO5X7ci/4JaD9rG8sKI0JKkhfhL0EyrzgWIykg4kCgYEAvy0eus9EDsEdSL2bNT0/Cd5wi/cEUVbhyLGhSXkjIxlIAHR7aU1L0qhaVE2VJ2Tp91tksGiw+gLvRoFne7sFnCqN/aNm1YhkkVW9QPYRv//B0tD595aOYhjRFwlM3ncekJcNmixnSHf78w3/+dZFgV8xKkOxiS8pVcREeBGxW20CgYBAbLuZbK0YE8ImiD1+u+oTBLNFoFQb0dw/UQqRIP+fcPulc8NDQUpwPeb1T5AYe0zWMIWEA6jKBg0o0DvZT3vS6L7A7YCEqt4ty6dxX/O+kIOXDBR9LB7y8z1sD2NGOWJ7hmipiRtStWQbkpj3yjJNVGqoB1gIYUdj2QHJndJhgQKBgQDTkCUFF0CgiBWUIyI96RkaSW/9/+3PAFojgHrbp93RLsW18j+YVZOyvQshhmNjlhEs2cONLYdNl5kPEi4yt/f8TrFbKBSgBlO0t9u0z0tAo+xfpocTzmYCw1eDnkXWxzZLwBSsB3Vkt7GJb11Uee7HW4MjHOTXuUvdQ8Alg+NXqw=="
    brPublicKey: "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA3QDuQlynuboCyAinT3gFxO/+FePOAT2HWVTKHsQqFje78BVdXVvAMo7DmL7zDmEnfzDgqhNLCuAjf03/Oe52pTKgOaFPjCBFJG2/islxV6TRYvyy4vBRhh0IE0BQEvk4pM9bB7WIN1vBu8ECbEwylxkO3RB/aSb90Wxmc0J05c4/9W6yfLgxl2JilT69jG7jprcws83fTtHDztXxFcKZyWwFH0MWZXjFC9tTqZJk46iAUHwDX/9uA42yXpWY0VAO2CEeNl6cRl1njpV0dQ948yDdJYLmnMMvnp9yb4WwuthOn9OK86rN004ZSsR+HIxWYzj76BppdmeN0tZOOpT47QIDAQAB"
    appId: "bairong"
    isProxy: true
  zbank: #众邦财富
    isPorxy: true
    api:
      baseUrl: "https://iodev-uat.z-bank.com"
      serverPubKey: "049191E0402CE98C8F31564880AC47AC888DACB24B127407D351AD83725CDB4529713E585CBB14C14E4EBBE97828D64B1F2DC101E113F227B6E6ACD9A378311DC3"
      appId: "2a0f9f71_29e5_466c_95a7_8cab99d93880"
      appSecretKey: "65ed7e3b-bcff-4f5b-a029-185a538e3ee8"
      priKey: "1DF4C616DE52063F5BB9525121160DF2F0607122A5FE69EB382D57020B27EA6A"
      serviceId:
        labelRating: "CMBrLabelRatingRe"
        CMBrScoDaFeBack: "CMBrScoDaFeBack"
    file:
      baseUrl: "https://iodev-uat.z-bank.com"
      channelId: "2023042701"
      encryptKey: "0463455a993b27010c80ceaca36f8faddcc5bb942b242faad8196ccda08d9ba556a669d6682d62d5278dbdc7a65d87ea8071635825725c35b92607eb379b369949"
      cksStr: "YRPZSSUEDOXHGNBYYYDGWPDASZJIIHXMJBZZFZTOSSHWABKGBHSBTUSJAMDFHIRX"
      slotKey: "rEFhYy7SRHzCrsMnzjqPoQ=="
  tongcheng:
    baseUrl: https://mns.qa.lylend.com
    address: ${api.tongcheng.baseUrl}/api/cep/agent/ret/baiRong
    isProxy: true
  mock:
    baseUrl: http://marketing-inner-api
    redisUrl: ${api.mock.baseUrl}/mockRedis/queryMockConfig

spring:
  rabbitmq:
    zw:
      addresses: delivery-rabbitmq-cluster-01.brapp.com:5672
      username: strategy_distribute
      password: strategy_distribute
      publisher-confirms: true
      publisher-returns: true
      virtual-host: marketing-flow
    yz:
      addresses: delivery-rabbitmq-cluster-01.brapp.com:5672
      username: strategy_distribute
      password: strategy_distribute
      publisher-confirms: true
      publisher-returns: true
      virtual-host: marketing-flow
    listener:
      retry:
        enabled: true
        max-attempts: 5
        initial-interval: 3000
      acknowledge-mode: manual
      default-requeue-rejected: false
      auto-startup: true
  web:
    interceptors.enabled: true
  sql.source: prod
cluster:
  flag: ${CONF_CLUSTER}
innerSftp:
  uploadpath: /UploadFiles/marketing/
#elastic-job配置
SERVER_LISTS: speed-zk-01.brapp.com:2181,speed-zk-02.brapp.com:2181,speed-zk-03.brapp.com:2181
NAMESPACE: marketing-job
BASE_SLEEP_TIME_MILLISECONDS: 1000
MAX_SLEEP_TIME_MILLISECONDS: 3000
MAX_RETRIES: 3
NESTED_PORT: -1
NESTED_DATA_DIR: target/test_zk_data/

rocketmq:
  # 多个NameServer，host:port;host:port，RocketMQProperties
  name-server: 10.100.123.171:9876;10.100.123.172:9876;10.100.123.173:9876
  producer:
    # 发送同一类消息的设置为同一个group，保证唯一
    group: Marketing_Default_Group
    # 发送消息失败重试次数，默认2
    retryTimesWhenSendFailed: 3
    # 异步消息重试此处，默认2
    retryTimesWhenSendAsyncFailed: 2
    # 发送消息超时时间，默认3000
    sendMessageTimeout: 5000
    # 消息最大长度，默认1024 * 1024 * 4(默认4M)
    maxMessageSize: 4194304
    # 压缩消息阈值，默认4k(1024 * 4)
    compressMessageBodyThreshold: 4096
    # 是否在内部发送失败时重试另一个broker，默认false
    retryNextServer: false
    # access-key
    #accessKey: xxx
    # secret-key
    #secretKey: xxx
    # 是否启用消息跟踪，默认false
    enableMsgTrace: false
    # 消息跟踪主题的名称值。如果不进行配置，可以使用默认的跟踪主题名称
    customizedTraceTopic: RMQ_SYS_TRACE_TOPIC
  consumer:
#    # 配置指定group是否启动监听器 group1.topic1 = false
#    listeners:
#      # key：group名称
#      rocketmq_source_code_group:
#        # value：{key: topic名称: value: true/false}
#        rocketmq_source_code: true
    # 指定消费组
    group: Marketing_Default_Group
    # 指定topic，启动时就会注册
    #topic: springboot_consumer_xxx
    # 一次拉取消息最大值，注意是拉取消息的最大值而非消费最大值
    pull-batch-size: 5
    # 其他配置参考属性类